import os
import streamlit as st

_get_env = lambda key: st.secrets.get(key) or os.environ.get(key, "")

ENV_FEATHERLESS_API_KEY = _get_env("FEATHERLESS_API_KEY")
ENV_QUERY_PLANNING_AGENT_LLM_MODEL = _get_env("QUERY_PLANNING_AGENT_LLM_MODEL")
ENV_PLOT_TYPE_CHOOSER_AGENT_LLM_MODEL = _get_env(
    "PLOT_TYPE_CHOOSER_AGENT_LLM_MODEL")
ENV_GOOGLE_API_KEY = _get_env("GOOGLE_API_KEY")
ENV_LLM_PROVIDER = _get_env("LLM_PROVIDER")
ENV_LEXICAL_ANALYSIS_AGENT_LLM_MODEL = _get_env(
    "LEXICAL_ANALYSIS_AGENT_LLM_MODEL")
ENV_NUMERIC_ANALYSIS_AGENT_LLM_MODEL = _get_env(
    "NUMERIC_ANALYSIS_AGENT_LLM_MODEL")
ENV_VISUAL_APPROPRIATENESS_AGENT_LLM_MODEL = _get_env(
    "VISUAL_APPROPRIATENESS_AGENT_LLM_MODEL")
ENV_FEATHERLESS_API_URL = _get_env("FEATHERLESS_API_URL")