import os
import streamlit as st

ENV_FEATHERLESS_API_KEY = st.secrets["FEATHERLESS_API_KEY"] or os.environ["FEATHERLESS_API_KEY"]
ENV_QUERY_PLANNING_AGENT_LLM_MODEL = st.secrets[
    "QUERY_PLANNING_AGENT_LLM_MODEL"] or os.environ["QUERY_PLANNING_AGENT_LLM_MODEL"]
ENV_PLOT_TYPE_CHOOSER_AGENT_LLM_MODEL = st.secrets[
    "PLOT_TYPE_CHOOSER_AGENT_LLM_MODEL"] or os.environ["PLOT_TYPE_CHOOSER_AGENT_LLM_MODEL"]
ENV_GOOGLE_API_KEY = st.secrets["GOOGLE_API_KEY"] or os.environ["GOOGLE_API_KEY"]
ENV_LLM_PROVIDER = st.secrets["LLM_PROVIDER"] or os.environ["LLM_PROVIDER"]
ENV_LEXICAL_ANALYSIS_AGENT_LLM_MODEL = st.secrets[
    "LEXICAL_ANALYSIS_AGENT_LLM_MODEL"] or os.environ["LEXICAL_ANALYSIS_AGENT_LLM_MODEL"]
ENV_NUMERIC_ANALYSIS_AGENT_LLM_MODEL = st.secrets[
    "NUMERIC_ANALYSIS_AGENT_LLM_MODEL"] or os.environ["NUMERIC_ANALYSIS_AGENT_LLM_MODEL"]
ENV_VISUAL_APPROPRIATENESS_AGENT_LLM_MODEL = st.secrets[
    "VISUAL_APPROPRIATENESS_AGENT_LLM_MODEL"] or os.environ["VISUAL_APPROPRIATENESS_AGENT_LLM_MODEL"]

